// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DialogController from "./dialog_controller.js"
application.register("dialog", DialogController)

import NotificationController from "./notification_controller.js"
application.register("notification", NotificationController)

import SelectionController from "./selection_controller.js"
application.register("selection", SelectionController)

import SelectionRowController from "./selection_row_controller.js"
application.register("selection-row", SelectionRowController)
