// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// Components
// -----------------------------------------------------------------------------
import NavbarController from "./components/navbar_controller"
application.register("navbar", NavbarController)

import AutocompleteController from "./components/autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import ModalController from "./components/modal_controller"
application.register("modal", ModalController)

import DropdownController from "./components/dropdown_controller"
application.register("dropdown", DropdownController)

import NoscriptController from "./components/noscript_controller"
application.register("noscript", NoscriptController)

import NotificationController from "./components/notification_controller"
application.register("notification", NotificationController)

import SelectionController from "./components/selection_controller"
application.register("selection", SelectionController)

import SelectionGroupController from "./components/selection_group_controller"
application.register("selection-group", SelectionGroupController)

import SelectionRowController from "./components/selection_row_controller"
application.register("selection-row", SelectionRowController)

// Forms
// -----------------------------------------------------------------------------
import DirectUploadFieldController from "./forms/direct_upload_field_controller"
application.register("direct-upload-field", DirectUploadFieldController)

import ReportFormController from "./forms/report_form_controller"
application.register("report-form", ReportFormController)

import UserFormController from "./forms/user_form_controller"
application.register("user-form", UserFormController)

