inherit_from: .rubocop_todo.yml

inherit_gem:
  action_policy: config/rubocop-rspec.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops:           enable
  DisplayCopNames:   true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'

# Layout -----------------------------------------------------------------------
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: false
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Layout/LineLength:
  Exclude:
    - 'db/seeds.rb'
    - 'spec/**/*'
  AllowedPatterns:
    - !ruby/regexp /\A\s*belongs_to/
    - !ruby/regexp /\A\s*belongs_to/
    - !ruby/regexp /\A\s*has_many/
    - !ruby/regexp /\A\s*has_one/
    - !ruby/regexp /\A\s*resources?/

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Exclude:
    - 'spec/**/*'

Layout/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*'

# Lint -------------------------------------------------------------------------
Lint/AmbiguousBlockAssociation:
  AllowedMethods:
    # These are usual methods in RSpec fluent syntax
    - change
    - satisfy

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'config/routes.rb'

# Metric -----------------------------------------------------------------------
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# Rails ------------------------------------------------------------------------
Rails/ActionOrder:
  ExpectedOrder:
    - index
    - show
    - new
    - create
    - edit
    - update
    - remove
    - destroy
    - undiscard
    - remove_all
    - destroy_all
    - undiscard_all

Rails/DynamicFindBy:
  AllowedMethods:
    # Method defined as User.find_by_invitation_token
    - find_by_invitation_token

Rails/Output:
  Exclude:
    - 'config/dotenv.rb'
    - 'db/seeds.rb'

Rails/SkipsModelValidations:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Exclude:
    # SQL queries passed to perform_sql_query matcher are squished by default
    - 'spec/**/*'

# RSpec ------------------------------------------------------------------------
RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectActual:
  Exclude:
    - 'spec/routing/**/*'  # expect(get: "/path) is a common pattern
    - 'spec/policies/**/*' # expect(:create?) is a common pattern

RSpec/FilePath:
  CustomTransform:
    ImportEPCIsDepartementsJob: import_epcis_departements_job
    ImportEPCIsJob: import_epcis_job
    DDFIPs: ddfips

RSpec/ImplicitSubject:
  EnforcedStyle: require_implicit

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/components/**/*'
    - 'spec/requests/**/*'
    - 'spec/system/**/*'

RSpec/NestedGroups:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Exclude:
    - 'spec/policies/**/*'

# Style ------------------------------------------------------------------------
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  AllowedVars:
    - BUNDLE_GEMFILE
    - RAILS_ENV

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/*'

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false
