test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cellar:
  service:            S3
  endpoint:           https://<%= Rails.application.credentials.dig(:cellar, :host) %>
  access_key_id:      <%= Rails.application.credentials.dig(:cellar, :access_key_id) %>
  secret_access_key:  <%= Rails.application.credentials.dig(:cellar, :secret_access_key) %>
  bucket:             <%= ENV.fetch("CELLAR_BUCKET") { Rails.application.credentials.dig(:cellar, :storage_bucket) } %>
  region:             eu-west
  force_path_style:   true
  upload:
    virtual_host: true
