# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**"
      - "!bin/*"
      - "!/*.md"
      - "!/**.md"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cache_dependencies:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'Skip CI') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby, install & cache Gems
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
        bundler-cache: true
    - name: Set up & cache Yarn
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'
    - name: Install JS packages
      run: yarn

  test_unit:
    name: test:unit
    needs: cache_dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        # Set N number of parallel jobs to run
        # Remember to update ci_node_index below to 0..N-1
        #
        ci_node_total: [4]
        ci_node_index: ["0,1", "2,3"]

    services:
      # Setup a postgres database to run tests
      #
      postgres:
        image: postgres:14.8
        env:
          POSTGRES_DB:       passerelle_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Ruby & install gems bundle
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
        bundler-cache: true

    - name: Set up Yarn
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'

    - name: Install JS packages
      run: yarn

    - name: Set up application
      env:
        CI:                  true
        CI_PARALLEL:         true
        POSTGRESQL_HOST:     localhost
        POSTGRESQL_PORT:     5432
        POSTGRESQL_USER:     postgres
        POSTGRESQL_PASSWORD: postgres
        POSTGRESQL_DATABASE: passerelle_test
      run: |
        bin/setup test

    - name: Run tests
      env:
        CI:                  true
        CI_PARALLEL:         true
        CI_NODE_TOTAL:       ${{ matrix.ci_node_total }}
        CI_NODE_INDEX:       ${{ matrix.ci_node_index }}
        RAILS_MASTER_KEY:    ${{ secrets.RAILS_MASTER_KEY }}
        POSTGRESQL_HOST:     localhost
        POSTGRESQL_PORT:     5432
        POSTGRESQL_USER:     postgres
        POSTGRESQL_PASSWORD: postgres
        POSTGRESQL_DATABASE: passerelle_test
      run: |
        bin/ci test unit

  test_system:
    name: test:system
    needs: cache_dependencies
    runs-on: ubuntu-latest
    services:
      # Setup a postgres database to run tests
      #
      postgres:
        image: postgres:14.8
        env:
          POSTGRES_DB:       passerelle_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Ruby & install gems bundle
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
        bundler-cache: true

    - name: Set up Yarn
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'

    - name: Install JS packages
      run: yarn

    - name: Set up application
      env:
        CI:                  true
        POSTGRESQL_HOST:     localhost
        POSTGRESQL_PORT:     5432
        POSTGRESQL_USER:     postgres
        POSTGRESQL_PASSWORD: postgres
        POSTGRESQL_DATABASE: passerelle_test
      run: |
        bin/setup test

    - name: Run tests
      env:
        CI:                  true
        RAILS_MASTER_KEY:    ${{ secrets.RAILS_MASTER_KEY }}
        POSTGRESQL_HOST:     localhost
        POSTGRESQL_PORT:     5432
        POSTGRESQL_USER:     postgres
        POSTGRESQL_PASSWORD: postgres
        POSTGRESQL_DATABASE: passerelle_test
        CAPYBARA_ARTIFACTS:  ./tmp/capybara
      run: |
        bin/ci test system --retry-failures

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: capybara-screenshots
        path: ./tmp/capybara

  rubocop:
    needs: cache_dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
        bundler-cache: true

    - name: Run rubocop
      run: |
        bin/ci rubocop

  brakeman:
    needs: cache_dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
        bundler-cache: true

    - name: Run brakeman
      run: |
        bin/ci brakeman

  audit:
    needs: cache_dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
        bundler-cache: true

    - name: Run audit
      run: |
        bin/ci audit
