# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI Experimentation

on:
  workflow_dispatch:

jobs:
  test_unit:
    name: test:unit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    services:
      # Setup a postgres database to run tests
      #
      postgres:
        image: postgres:14.8
        env:
          POSTGRES_DB:       fiscahub_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Ruby & install gems bundle
      uses: ruby/setup-ruby@v1
      env:
        BUNDLE_GEMS__CONTRIBSYS__COM: ${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}
      with:
        ruby-version: 3.2.2
        bundler-cache: true

    - name: Set up Yarn
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'

    - name: Install JS packages
      run: yarn

    - name: Set up application
      env:
        CI:                  true
        CI_PARALLEL:         true
        POSTGRESQL_HOST:     localhost
        POSTGRESQL_PORT:     5432
        POSTGRESQL_USER:     postgres
        POSTGRESQL_PASSWORD: postgres
        POSTGRESQL_DATABASE: fiscahub_test
      run: |
        bin/setup test

    - name: Run tests
      env:
        CI:                  true
        CI_PARALLEL:         true
        CI_NODE_TOTAL:       2
        RAILS_MASTER_KEY:    ${{ secrets.RAILS_MASTER_KEY }}
        POSTGRESQL_HOST:     localhost
        POSTGRESQL_PORT:     5432
        POSTGRESQL_USER:     postgres
        POSTGRESQL_PASSWORD: postgres
        POSTGRESQL_DATABASE: fiscahub_test
      run: |
        bin/ci test spec/components
